front:
  build: .
  container_name: front
  hostname : "rabih-work"
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql:mysql
    - mongo:mongo
    - memcached:memcached
    - redis:redis
    - elasticsearch:elasticsearch
    - rabbitmq:rabbitmq
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

mysql:
  build: ./docker/mysql/
  container_name: mysql
  ports:
    - "3306:3306"
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: password
data:
  build: ./docker/mysql/
  container_name: mysqldata
  volumes:
    - /var/lib/mysql
  command: "true"
phpmyadmin:
  build: ./docker/phpmyadmin/
  container_name: phpmyadmin
  ports:
    - "8080:80"
  links:
    - mysql
  environment:
    PMA_HOST: mysql
mongo:
  build: ./docker/mongo/
  container_name: mongo
  ports:
    - "27017:27017"

memcached:
  build: ./docker/memcached/
  container_name: memcached
  ports:
    - "11211:11211"

redis:
  build: ./docker/redis/
  container_name: redis
  ports:
    - "6379:6379"

elasticsearch:
  build: ./docker/elasticsearch/
  container_name: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

rabbitmq:
  build: ./docker/rabbitmq/
  container_name: rabbitmq
  ports:
    - "15672:15672"
    - "5672:5672"
